; PlatformIO Project Configuration File
; ESP32 BLE Project for CogniMirror Cube

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
upload_speed = 921600

; Configuracion adicional para BLE
build_flags = 
    -D CONFIG_BT_ENABLED=1
    -D CONFIG_BLUEDROID_ENABLED=1
